repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Remove end of file
  - repo: local
    hooks:
      - id: pylint
        name: Code quality
        entry: ./venv/bin/pylint .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: pytest
        name: Tests and Coverage
        entry: ./venv/bin/pytest --cov=source --cov-fail-under=80 tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
