repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./venv/bin/pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: pylint
        name: pylint
        entry: ./venv/bin/pylint .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
